# Generated by Django 3.1.1 on 2020-10-19 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('program_branch', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('yearofadmission', models.CharField(max_length=50)),
                ('year_of_passing_out', models.CharField(max_length=50)),
                ('About_you', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('official_id', models.CharField(max_length=50)),
                ('year_of_passout', models.CharField(max_length=50)),
                ('Current_job', models.CharField(max_length=50)),
                ('Branch_in_undergrad', models.CharField(max_length=50)),
                ('college_gpa', models.CharField(max_length=50)),
                ('Examination_taken', models.CharField(max_length=50)),
                ('Job_Sector', models.CharField(max_length=50)),
                ('Previous_company', models.CharField(max_length=50)),
                ('current_company', models.CharField(max_length=50)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('About_you', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Alumni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
