# Generated by Django 3.1.1 on 2020-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20201019_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='status',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
