# Generated by Django 3.1.1 on 2020-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20201020_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='hobbies',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumni',
            name='internships',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumni',
            name='tech_known',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='internships',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='tech_known',
            field=models.CharField(default='', max_length=50),
        ),
    ]
