# Generated by Django 3.1.1 on 2020-10-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumni_noofviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='noofviews',
            field=models.IntegerField(default=0),
        ),
    ]
