# Generated by Django 3.1.1 on 2020-10-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20201027_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='second_name',
            new_name='secondname',
        ),
    ]
