# Generated by Django 3.1.1 on 2020-11-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_auto_20201113_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
